apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/components/operators/gpu-operator-certified/operator/overlays/stable
