---
# Source: minio/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: minio
  labels:
    app: minio
    chart: minio-5.2.0
    release: minio
    heritage: Helm
type: Opaque
data:
  rootUser: "cm9vdHVzZXI="
  rootPassword: "cm9vdHVzZXIxMjM="
